name: Build and Inject into LXC Container

on:
  workflow_dispatch:

jobs:
  build:
    name: Build LXC RootFS and Inject
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt install -y debos wget qemu-user-static snapd
          sudo snap install lxd

      - name: Download rootfs
        run: |
          mkdir -p base
          wget https://images.linuxcontainers.org/images/debian/trixie/arm64/cloud/20250420_05:24/rootfs.tar.xz -O base/rootfs.tar.xz
          # Menambahkan file public-key.asc jika perlu
          cp public-key.asc base/public-key.asc

      - name: Initialize LXD
        run: |
          if ! sudo lxd init --auto; then
            echo "LXD initialization failed."
            exit 1
          fi

      - name: Create LXC Storage Pool
        run: |
          sudo lxc storage create lxd-pool dir

      - name: Create LXC container with Debian Trixie rootfs
        run: |
          # Buat container kosong dan tambahkan rootfs ke container
          sudo lxc init debian trixie-container --empty
          sudo lxc config device add trixie-container root disk path=/ source=base/rootfs.tar.xz

      - name: Start LXC container
        run: |
          sudo lxc start trixie-container

      - name: Inject packages and configure container
        run: |
          # Jalankan injeksi ke dalam container dengan skrip lindroid.plasma.yml atau melalui perintah lainnya
          sudo lxc exec trixie-container -- bash -c "
            # Eksekusi perintah setup yang diinginkan dalam container
            apt update
            apt install -y sudo lindroid-quirks kde-full kwin-wayland
            useradd -m -s /bin/bash lindroid
            echo 'lindroid:lindroid' | chpasswd
            systemctl enable ssh
            systemctl enable sddm
          "

      - name: Clean up APT cache
        run: |
          sudo lxc exec trixie-container -- apt clean

      - name: Repack LXC container rootfs
        run: |
          sudo lxc stop trixie-container
          sudo lxc export trixie-container out/lindroid-custom-rootfs.tar.xz

      - name: Upload custom rootfs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lindroid-custom-rootfs
          path: out/lindroid-custom-rootfs.tar.xz
          retention-days: 1
