name: Build Lindroid RootFS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Inject Lindroid Packages

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y debos qemu-user-static xz-utils

      - name: Copy public-key
        run: sudo cp public-key.asc /root/public-key.asc

      - name: Run Debos
        run: sudo debos --disable-fakemachine inject.yaml

      - name: Upload Final RootFS
        uses: actions/upload-artifact@v4
        with:
          name: lindroid-rootfs
          path: out/lindroid-rootfs.tar.gz
