name: Build Lindroid RootFS inject

on:
  workflow_dispatch:

jobs:
  build:
    name: Build RootFS
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y debos wget qemu-user-static

      - name: Download rootfs
        run: |
          wget https://images.linuxcontainers.org/images/debian/trixie/arm64/cloud/20250420_05:24/rootfs.tar.xz -O base/rootfs.tar.xz
          cp public-key.asc base/public-key.asc

      - name: Extract rootfs
        run: |
          mkdir -p rootfs
          tar -xf base/rootfs.tar.xz -C rootfs

      - name: Run Debos
        run: |
          sudo debos --disable-fakemachine inject.yaml

      - name: Upload final RootFS as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lindroid-custom-rootfs
          path: out/lindroid-custom-rootfs.tar.gz
          retention-days: 1
