name: Build and Inject into LXC Container teat 2

on:
  workflow_dispatch:

jobs:
  build:
    name: Build LXC RootFS and Inject
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt install -y debos wget qemu-user-static snapd
          sudo snap install lxd

      - name: Download rootfs
        run: |
          mkdir -p base
          wget https://images.linuxcontainers.org/images/debian/trixie/arm64/cloud/20250420_05:24/rootfs.tar.xz -O base/rootfs.tar.xz
          # Tambahkan public-key jika perlu
          cp public-key.asc base/public-key.asc || true

      - name: Initialize LXD
        run: |
          sudo lxd init --auto

      - name: Import rootfs as LXC image
        run: |
          mkdir -p base/rootfs
          tar -xf base/rootfs.tar.xz -C base/rootfs

          echo "architecture: arm64
          creation_date: $(date +%s)
          properties:
            description: Debian Trixie rootfs
            os: debian
            release: trixie" > base/metadata.yaml

          cd base
          tar -cf ../debian-trixie.tar metadata.yaml rootfs
          cd ..

          sudo lxc image import debian-trixie.tar --alias debian-trixie

      - name: Create LXC container from image
        run: |
          sudo lxc init debian-trixie trixie-container
          sudo lxc start trixie-container
          sleep 10
          sudo lxc exec trixie-container -- touch /.container-ready

      - name: Inject packages and configure container
        run: |
          sudo lxc exec trixie-container -- bash -c "
            apt update
            apt install -y sudo lindroid-quirks kde-full kwin-wayland
            useradd -m -s /bin/bash lindroid
            echo 'lindroid:lindroid' | chpasswd
            systemctl enable ssh
            systemctl enable sddm
          "

      - name: Clean up APT cache
        run: |
          sudo lxc exec trixie-container -- apt clean

      - name: Repack LXC container rootfs
        run: |
          mkdir -p out
          sudo lxc stop trixie-container
          sudo lxc export trixie-container out/lindroid-custom-rootfs.tar.xz

      - name: Upload custom rootfs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lindroid-custom-rootfs
          path: out/lindroid-custom-rootfs.tar.xz
          retention-days: 1
